# Generated by Django 4.2.8 on 2024-01-04 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_connection_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='bookmarked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='progress',
            field=models.CharField(choices=[('P', 'Pending'), ('I', 'Interviewing'), ('O', 'Offer Extended'), ('R', 'Rejected')], default='P', max_length=1),
        ),
    ]
