# Generated by Django 4.2.8 on 2024-01-05 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_job_bookmarked_job_location_job_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='date',
            field=models.DateField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='status',
            name='description',
            field=models.TextField(max_length=200, verbose_name='Add New Status Update'),
        ),
    ]
